# Generated by Django 4.2.23 on 2025-07-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='codigo_item_manual',
            field=models.CharField(blank=True, help_text='Código manual do item no orçamento (ex: P01)', max_length=50, null=True),
        ),
    ]
