# Generated by Django 4.2.23 on 2025-07-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_configuracaoatributo_produtoconfiguracao_and_more'),
        ('orcamentos', '0002_itemorcamento_codigo_item_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='configuracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produtoconfiguracao'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orcamentos.itemorcamento'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.produtoinstancia'),
        ),
    ]
