# Generated by Django 4.2.23 on 2025-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_itemorcamento_configuracao_itemorcamento_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='margem_negocio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
