# Generated by Django 4.2.23 on 2025-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_itemorcamento_margem_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='margem_negocio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
