# Generated by Django 4.2.23 on 2025-07-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtotemplate',
            name='unidade',
            field=models.CharField(blank=True, help_text='Unidade de medida do produto (ex: m², unidade, kg)', max_length=50, null=True),
        ),
    ]
