# Generated by Django 4.2.23 on 2025-07-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtotemplate_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='instanciacomponente',
            name='item_material',
        ),
        migrations.RemoveField(
            model_name='instanciacomponente',
            name='unidade',
        ),
        migrations.AddField(
            model_name='templatecomponente',
            name='atributo_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes_relacionados', to='produtos.templateatributo'),
        ),
        migrations.AddField(
            model_name='templatecomponente',
            name='multiplicador',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='templatecomponente',
            name='quantidade_fixa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='templatecomponente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instanciacomponente',
            name='componente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.componente'),
        ),
        migrations.AddField(
            model_name='templatecomponente',
            name='componente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.componente'),
        ),
        migrations.AlterUniqueTogether(
            name='templatecomponente',
            unique_together={('template', 'componente')},
        ),
        migrations.RemoveField(
            model_name='templatecomponente',
            name='item_material',
        ),
        migrations.RemoveField(
            model_name='templatecomponente',
            name='quantidade_expr',
        ),
        migrations.RemoveField(
            model_name='templatecomponente',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='ItemMaterial',
        ),
    ]
