# Generated by Django 4.2.23 on 2025-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_componente_remove_instanciacomponente_item_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciacomponente',
            name='descricao_detalhada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
