# Generated by Django 4.2.23 on 2025-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_instanciacomponente_descricao_detalhada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecomponente',
            name='multiplicador',
        ),
        migrations.AddField(
            model_name='templatecomponente',
            name='formula_calculo',
            field=models.TextField(blank=True, help_text="Fórmula Python para calcular a quantidade. Use 'valor_atributo' para o valor do atributo relacionado. Ex: 'valor_atributo * 3' ou '10 + (valor_atributo / 2)'. CUIDADO: Código Python será avaliado."),
        ),
    ]
