# Generated by Django 4.2.23 on 2025-07-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_templatecomponente_multiplicador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.CharField(blank=True, max_length=200)),
                ('valor_num', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.templateatributo')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Janela 1.20x1.50, Vidro Duplo', max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='produtos.produtotemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='instanciacomponente',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='instanciacomponente',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='produtoinstancia',
            name='template',
        ),
        migrations.AlterField(
            model_name='templatecomponente',
            name='formula_calculo',
            field=models.TextField(blank=True, help_text="Fórmula Python para calcular a quantidade do componente. \n\n**Variáveis disponíveis:**\n- `valor_atributo`: O valor do atributo selecionado em 'Atributo Relacionado'.\n- Nomes dos atributos da instância (ex: `altura`, `largura`, `numero_de_folhas`). Espaços são substituídos por underscores e letras minúsculas.\n- `math`: Módulo Python `math` para funções como `math.ceil()`, `math.floor()`, etc.\n\n**Exemplos:**\n- `valor_atributo * 3` (se 'Atributo Relacionado' for 'Número de Folhas')\n- `altura / 1000 * 2` (se 'altura' for um atributo da instância)\n- `math.ceil(altura / 1200) * numero_de_folhas` (para dobradiças por altura e folhas)\n- `10 + (largura / 500)` (quantidade base + variável)\n\n**CUIDADO:** Esta fórmula é avaliada como código Python. Use apenas com fontes confiáveis.\n"),
        ),
        migrations.DeleteModel(
            name='InstanciaAtributo',
        ),
        migrations.DeleteModel(
            name='InstanciaComponente',
        ),
        migrations.AddField(
            model_name='configuracaoatributo',
            name='configuracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='produtos.produtoconfiguracao'),
        ),
        migrations.AddField(
            model_name='produtoinstancia',
            name='configuracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='produtos.produtoconfiguracao'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaoatributo',
            unique_together={('configuracao', 'atributo')},
        ),
    ]
