# Generated by Django 4.2.23 on 2025-07-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_configuracaoatributo_produtoconfiguracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComponenteEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_real', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.componente')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.CharField(blank=True, max_length=200)),
                ('valor_num', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='produtos.produtoinstancia')),
                ('template_atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.templateatributo')),
            ],
            options={
                'unique_together': {('instancia', 'template_atributo')},
            },
        ),
        migrations.CreateModel(
            name='InstanciaComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao_detalhada', models.CharField(blank=True, max_length=255, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.componente')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produtos.produtoinstancia')),
            ],
        ),
        migrations.AlterField(
            model_name='produtoconfiguracao',
            name='nome',
            field=models.CharField(help_text='Ex: Acabamento Fosco, Dobradiças Standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='produtoconfiguracao',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes', to='produtos.produtotemplate'),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoAtributo',
        ),
        migrations.AddField(
            model_name='configuracaocomponenteescolha',
            name='configuracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_escolha', to='produtos.produtoconfiguracao'),
        ),
        migrations.AddField(
            model_name='configuracaocomponenteescolha',
            name='template_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.templatecomponente'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaocomponenteescolha',
            unique_together={('configuracao', 'template_componente')},
        ),
    ]
