# Generated by Django 4.2.23 on 2025-07-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_configuracaocomponenteescolha_instanciaatributo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('opcional', models.BooleanField(default=False)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.componente')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_configuracao', to='produtos.produtoconfiguracao')),
            ],
            options={
                'unique_together': {('configuracao', 'componente')},
            },
        ),
    ]
