# Generated by Django 4.2.23 on 2025-07-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_configuracaocomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocomponenteescolha',
            name='descricao_personalizada',
            field=models.CharField(blank=True, help_text="Descrição personalizada para este componente na configuração (ex: 'LAC. RAL 9010', 'REF JNF XPTO')", max_length=255, null=True),
        ),
    ]
