# Generated by Django 4.2.23 on 2025-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_configuracaocomponenteescolha_descricao_personalizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtotemplate',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produtoconfiguracao',
            name='descricao_configuracao_template',
            field=models.TextField(blank=True, help_text='Template para a descrição da configuração (ex: para o agrupador no orçamento). Use variáveis de componentes como {{ componentes.fechadura }}.'),
        ),
        migrations.AddField(
            model_name='produtotemplate',
            name='descricao_instancia_template',
            field=models.TextField(blank=True, help_text='Template para a descrição da instância individual (ex: para a linha do orçamento). Use variáveis de atributos como {{ altura }}.'),
        ),
    ]
