# Generated by Django 4.2.23 on 2025-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoriaitem_codigo_categoria_and_more'),
        ('produtos', '0010_remove_produtotemplate_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='itens_compativeis',
            field=models.ManyToManyField(blank=True, related_name='componentes_conceptuais', to='estoque.itemestocavel'),
        ),
    ]
