# Generated by Django 4.2.23 on 2025-07-31 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumos', '0004_remove_sessaotrabalho_ref_obra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Ferragens, Painéis de Madeira, Consumíveis', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='estoque.categoriaitem')),
            ],
            options={
                'verbose_name': 'Categoria de Item',
                'verbose_name_plural': 'Categorias de Itens',
                'unique_together': {('nome', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='ItemEstocavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Painel MDF Hidrófugo 19mm 2440x1220', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Detalhes técnicos, fornecedor, etc.')),
                ('codigo_sku', models.CharField(help_text='SKU (Stock Keeping Unit) ou código de barras único do item.', max_length=100, unique=True)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('m', 'Metro Linear'), ('m2', 'Metro Quadrado'), ('m3', 'Metro Cúbico'), ('kg', 'Quilograma'), ('L', 'Litro')], default='un', max_length=5)),
                ('largura_mm', models.PositiveIntegerField(blank=True, help_text='Largura em milímetros', null=True)),
                ('altura_mm', models.PositiveIntegerField(blank=True, help_text='Altura ou comprimento em milímetros', null=True)),
                ('espessura_mm', models.PositiveIntegerField(blank=True, help_text='Espessura em milímetros', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='estoque.categoriaitem')),
            ],
            options={
                'verbose_name': 'Item Estocável',
                'verbose_name_plural': 'Itens Estocáveis',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_inicial', models.DecimalField(decimal_places=4, help_text='Quantidade que entrou neste lote.', max_digits=12)),
                ('quantidade_atual', models.DecimalField(decimal_places=4, help_text='Quantidade que ainda resta neste lote.', max_digits=12)),
                ('custo_unitario_compra', models.DecimalField(decimal_places=4, help_text='Custo de compra por unidade deste lote.', max_digits=10)),
                ('data_entrada', models.DateField(auto_now_add=True, help_text='Data em que o lote entrou em armazém.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.itemestocavel')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, help_text='Quantidade movimentada. Positiva para entradas, negativa para saídas.', max_digits=12)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra)'), ('SAIDA', 'Saída (Consumo de Produção)'), ('AJUSTE_P', 'Ajuste Positivo'), ('AJUSTE_N', 'Ajuste Negativo')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.lote')),
                ('origem_consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='consumos.itemconsumido')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-timestamp'],
            },
        ),
    ]
