# Generated by Django 4.2.23 on 2025-07-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaitem',
            name='codigo_categoria',
            field=models.CharField(help_text='Prefixo único para esta categoria (ex: FER, PNL, QMC).', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itemestocavel',
            name='codigo_interno_gerado',
            field=models.CharField(editable=False, help_text='Código interno completo gerado automaticamente (ex: PNL-0001).', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='itemestocavel',
            name='codigo_interno_item',
            field=models.PositiveIntegerField(editable=False, help_text='Código sequencial do item dentro da categoria.', null=True),
        ),
        migrations.AddField(
            model_name='itemestocavel',
            name='codigo_sku_fornecedor',
            field=models.CharField(blank=True, help_text='SKU (Stock Keeping Unit) ou código de barras do fornecedor.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='itemestocavel',
            unique_together={('categoria', 'codigo_interno_item')},
        ),
        migrations.RemoveField(
            model_name='itemestocavel',
            name='codigo_sku',
        ),
    ]
