# Generated by Django 4.2.23 on 2025-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoriaitem_codigo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações ou justificativa para o movimento.', null=True),
        ),
    ]
