# Generated by Django 4.2.23 on 2025-07-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaConsumoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_obra', models.CharField(help_text='O código ou nome único da obra', max_length=100, unique=True)),
                ('data_inicio', models.DateField(help_text='A data de início dos trabalhos na obra')),
                ('previsao_entrega', models.DateField(help_text='A data prevista para a conclusão')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_consumo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Serra de Bancada, CNC 1, Bancada de Montagem', max_length=100, unique=True)),
                ('custo_hora', models.DecimalField(decimal_places=2, help_text='Custo operacional por hora do posto', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_obra', models.CharField(help_text='O código da obra sendo trabalhada', max_length=100)),
                ('operacao', models.TextField(help_text='Descrição da tarefa realizada')),
                ('hora_inicio', models.DateTimeField(help_text='Data e hora de início da tarefa')),
                ('hora_saida', models.DateTimeField(blank=True, help_text='Data e hora de término da tarefa', null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_trabalho', to=settings.AUTH_USER_MODEL)),
                ('posto_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_trabalho', to='consumos.postotrabalho')),
            ],
        ),
        migrations.CreateModel(
            name='ItemConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consumo', models.DateField(help_text='O dia em que o material foi efetivamente consumido')),
                ('object_id', models.PositiveIntegerField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(help_text='Ex: m, kg, un', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ficha_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_consumidos', to='consumos.fichaconsumoobra')),
            ],
        ),
    ]
