# Generated by Django 4.2.23 on 2025-07-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_configuracaocomponente'),
        ('consumos', '0002_operador_alter_sessaotrabalho_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconsumido',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemconsumido',
            name='object_id',
        ),
        migrations.AddField(
            model_name='itemconsumido',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_itens', to='produtos.componente'),
        ),
        migrations.AddField(
            model_name='itemconsumido',
            name='descricao_detalhada',
            field=models.CharField(blank=True, help_text='Ex: HTD-H1000, Cor: Branco', max_length=255, null=True),
        ),
    ]
