# Generated by Django 4.2.23 on 2025-07-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0003_remove_itemconsumido_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaotrabalho',
            name='ref_obra',
        ),
        migrations.AddField(
            model_name='sessaotrabalho',
            name='ficha_obra',
            field=models.ForeignKey(blank=True, help_text='A ficha de consumo de obra à qual esta sessão de trabalho está relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_trabalho_relacionadas', to='consumos.fichaconsumoobra'),
        ),
    ]
