# Generated by Django 4.2.23 on 2025-07-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoriaitem_codigo_categoria_and_more'),
        ('consumos', '0004_remove_sessaotrabalho_ref_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemconsumido',
            name='componente',
        ),
        migrations.AddField(
            model_name='itemconsumido',
            name='item_estocavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='estoque.itemestocavel'),
        ),
    ]
